project_name: iptv-proxy

builds:
  - binary: iptv-proxy
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux
      - openbsd

    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-u", "pierre-emmanuel.jacquier@epitech.eu", "--detach-sign", "${artifact}"]
  artifacts: all

archive:
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: pierre-emmanuelJ
    name: iptv-proxy
  draft: true

nfpm:
  vendor: Pierre-Emmanuel
  homepage: https://github.com/pierre-emmanuelJ/iptv-proxy
  maintainer: Pierre-Emmanuel <pierre-emmanuel.jacquier@epitech.eu>
  description: Reverse proxy on iptv m3u file
  license: Apache 2.0
  formats:
    - deb
    - rpm

brew:
  github:
    owner: pierre-emmanuel
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/pierre-emmanuelJ/iptv-proxy"
  description: Reverse proxy on iptv m3u file