name: Docker Image CI/CD

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iptv-proxy:$(git describe --abbrev=0 --tags 2>/dev/null)

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pierre-emmanuelj/iptv-proxy/iptv-proxy
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
